config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:new, :create, :show, :index]
  resources :games, only: [:index, :show, :new, :create] do 
    resources :comments, only: [:create]
  end

  devise_for :users
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :comments
  has_many :users, through: :comments
  validates :rank, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :games, through: :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(user: current_user, game_id: params[:game_id], comment: params[:comment][:comment])
    if @comment.save
      redirect_to game_path(@comment.game)
    else
      render :new
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @comment = Comment.new
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

private

  def game_params
    params.require(:game).permit(:title, :description, :rank, :photo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/index.html.erb
<div class= "game_show">
  <h1>My Comments</h1>
  <% current_user.comments.each do |comment| %>
  <ul class= "comment_list">
    <li>
      Game: <%= comment.game.title %>
      <br/>
      Comment: <%= comment.comment %>
      <br/>
    </li>
  </ul>
  <% end %>
</div>

app/views/games/index.html.erb
<h1>Games</h1>

<% @games.each do |game| %>
<ul class="game_cards">
  <li>
    <%= link_to image_tag(game.photo, width: "auto", height: 300), game_path(game), class: "index_game_pictures" %><br/>
    Title: <%= game.title %><br/>
    Description: <%= game.description %><br/>
    Rating: <%= game.rank %><br/>
    <%= button_to "View Game", game_path(game), method: :get, class: "game_view" %>
  </li>
</ul>
<% end %>

app/views/games/new.html.erb
<h1 class = "new_game_title">Add a new Game!</h1>
<div class = "new_game_form">
  <%= form_for @game do |form| %>
    <%= form.text_field :title, placeholder: "Title" %>
    <br/>
    <%= form.text_field :description, placeholder: "Description" %>
    <br/>
    <small>Add a description of the game above</small>
    <br/>
    <%= form.text_field :rank, placeholder: "Rating" %>
    <br/>
    <small>Rate the game on a scale from 1-10</small>
    <br/>
    <%= form.text_field :photo, placeholder: "Photo Url" %>
    <br/>
    <small>Add an image url to be displayed</small>
    <br/>
    <%= form.submit%>
  <% end %>

  <% if @game.errors.any? %>
  <p> 
    <%= @game.errors.full_messages %>
  </p>
  <% end %>
</div>

app/views/games/show.html.erb
<div class= "game_show">
  <div class= "field">
    <%=image_tag(@game.photo) %><br/>
  </div>
  <%= @game.title %><br/>
  <div class = "field">
  <%= form_for [@game, @comment] do |form| %>
    <%= form.text_field :comment, placeholder: "Add New Comment" %>
    <br/>
    </div>
    <%= form.submit%>
    <br/>
  <% end %>
  <div class= "comment_container">
  <label>Comments: </label>
  <% @game.comments.order(created_at: :desc).each do |comment| %>
    <ul class= "game_comments">
      <li>
        <%= comment.user.name %>:
        <%= comment.comment %>
      </li>
    </ul>
  <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% name = current_user.present? ? ", #{current_user.name}" : ", click Sign In to continue" %>
<div class= "home_index">
  <h1>Welcome<%= name %></h1>
</div>
<div class= "home_index">
  <p>Welcome to the Video Game Reviewer App</p>
  <p>Browse games, add games, and leave comments on those games!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videogamereviewer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Video Game Reviewer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Games', games_path, class: 'nav-link' %>
          </li>
            <li class="nav-item">
              <%= link_to 'Add New Game', new_game_path, class: 'nav-link' %>
            </li>
             <li class="nav-item">
              <%= link_to 'My Comments', comments_path, class: 'nav-link' %>
            </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>